version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - petclinic-net

  spring-petclinic:
    image: spring-petclinic:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-petclinic
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    networks:
      - petclinic-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - petclinic-net

  jdk17:
    image: openjdk:17-jdk
    container_name: jdk17
    working_dir: /workspace
    volumes:
      - ./:/workspace
    networks:
      - petclinic-net
    entrypoint: ["tail", "-f", "/dev/null"]

  jdk21:
    image: openjdk:21
    container_name: jdk21
    working_dir: /workspace
    volumes:
      - ./:/workspace
    networks:
      - petclinic-net
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:

networks:
  petclinic-net:
