version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - petclinic-net

  build-java8:
    image: openjdk:8-jdk
    container_name: build-java8
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean compile
    networks:
      - petclinic-net

  test-java11:
    image: openjdk:11-jdk
    container_name: test-java11
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn test
    networks:
      - petclinic-net

  sonar-java17:
    image: openjdk:17-jdk
    container_name: sonar-java17
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      SONAR_HOST_URL: http://localhost:9000
      SONAR_TOKEN: ${SONAR_TOKEN}
    command: >
      bash -c "mvn sonar:sonar
        -Dsonar.projectKey=spring-petclinic
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN"
    networks:
      - petclinic-net

  app:
    image: spring-petclinic:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-petclinic
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    networks:
      - petclinic-net

volumes:
  db_data:

networks:
  petclinic-net:
