version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - petclinic-net

  app:
    image: spring-petclinic:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-petclinic
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    networks:
      - petclinic-net

  java8:
    build:
      context: .
      dockerfile: Dockerfile-java8
    container_name: java8
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    networks:
      - petclinic-net

  java11:
    build:
      context: .
      dockerfile: Dockerfile-java11
    container_name: java11
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    networks:
      - petclinic-net

  java17:
    build:
      context: .
      dockerfile: Dockerfile-java17
    container_name: java17
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    networks:
      - petclinic-net

volumes:
  db_data:

networks:
  petclinic-net:
